databases:
  - name: quiz
    databaseName: quiz
    user: quiz

services:
  - type: web
    name: quiz
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false